config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root             'static_pages#home'
  get 'contattaci'    => 'static_pages#contattaci'
  get 'lavori'   => 'static_pages#INostriLavori'
  get 'dovesiamo' => 'static_pages#Dovesiamo'
  get 'signup' => 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contattaci
  end

  def INostriLavori
  end

  def Dovesiamo
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Cut Down Records"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <footer class="footer">
      <div class="center">
          <input id="email" type="email" class="validate center white black-text" placeholder="Inserisci qui la tua email!">
          <br>
            <button class="btn btn-lg btn-danger" type="submit" name="action">Voglio Registrarmi alla Newsletter!</button>
        </div>
          <div class="center">
          <h5 style="color: #fff; font-size: 1.8em">Contattaci e Seguici</h5>
          <br>
          <a href="https://wa.me/393891086664" class="icon-footer" target="_blank"><i class="fab fa-whatsapp"></i></a>
          <a href="mailto:cutdownrecords2017@gmail.com" class="icon-footer" target="_blank"><i class="fa fa-envelope"></i></a>
          <a href="https://m.me/Cutdownrecords?fbclid=IwAR11xCvca_lH-i67cwr6WR5kYKES7ZCUWlD9K4MjBGpPsrdwSsd65Y0VwE0" class="icon-footer" target="_blank"><i class="fab fa-facebook-messenger"></i></a>
          <a href="https://www.facebook.com/pg/Cutdownrecords/posts/?ref=page_internal" class="icon-footer" target="_blank"><i class="fab fa-facebook-square"></i></a>
          <a href="https://www.instagram.com/cutdownrecords/?hl=it" class="icon-footer" target="_blank"><i class="fab fa-instagram"></i></a>
          <a href="https://www.youtube.com/channel/UClRNlBbbKLEqBLtA31I1goQ" class="icon-footer" target="_blank"><i class="fab fa-youtube"></i></a>
          <br>
<div class="container">
            <small>
          <p>2020 &copy Oigres WD</p>
        </small>
      </div>
          </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Cut Down Records", root_path, id: "logo" %>
        <nav>
          <div class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" style="color: #b71c1c; font-size: 1.5em">Menu
              <span class="caret"></span></a>
              <ul id="dropdownm" class="dropdown-menu dropdown-menu-right">
                <li><%= link_to "Home", root_path %></li>
                 <li><%= link_to "Contattaci", contattaci_path %></li>
                <li><%= link_to "i Nostri Lavori", lavori_path %></li>
                <li><%= link_to "Dove Siamo", dovesiamo_path %></li>
                </ul>
          </div>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <!-- Font aweson icon -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


<script src="https://kit.fontawesome.com/4ec30d7b7a.js" crossorigin="anonymous"></script>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<!-- Meta -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Cut Down Records - Project studio</title>
  <meta name="description" content="Con una sala di registrazione adeguatamente insonorizzata e regia in locale separato abbiamo strumenti che ci permettono di avere risultati professionali. Offriamo servizi di mixing e mastering con ottimi prezzi e offerte per le prime prove.">
  <meta name=”keywords” content="Studio sala registrazione project professionale polanesi sori genova liguria  offerte promozioni registrare gruppo band musicale ottimo suono qualità audio eccellente mixing mastering recording disco album montaggio audio video videoclip riprese presa diretta insonorizzazione">


<!-- Google Font -->
 <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji+2|Rock+Salt&display=swap" rel="stylesheet">

  </head>
  <body >
        <%= render 'layouts/header' %>
      <%= yield %>
         <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/Dovesiamo.html.erb
<% provide(:title, 'Dove Siamo') %>
<div class="dove">
	<div class="container">
		<div class="center">
			<h1 style="color: #b71c1c; text-shadow: 3px 3px 6px #3e2723">Ecco dove puoi trovarci</h1>
			<br>
			<br>
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1426.1282835596485!2d9.119265758244502!3d44.366321294775794!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12d35e66513e6907%3A0x5b1ad38cbe142efb!2sVia%20Polanesi%2C%2017%2C%2016031%20Sori%20GE!5e0!3m2!1sit!2sit!4v1586993850318!5m2!1sit!2sit" width="600" height="450" frameborder="0" style="border:2px solid #ccc; margin-bottom: 10%; margin-top: 5%" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
			<iframe src="https://www.google.com/maps/embed?pb=!4v1586994185630!6m8!1m7!1s9sLH5tpkkFvYluo2vGn-lg!2m2!1d44.36659883811225!2d9.119330625715785!3f343.9329759602348!4f-13.685249607793807!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:2px solid #ccc; margin-bottom: 10%;  margin-top: 5%" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
		</div>
	</div>
</div>

app/views/static_pages/INostriLavori.html.erb
<% provide(:title, "I Nostri Lavori") %>
<div class="lavori">
<div class="container">
	<div class="center">
		<h1 style="color: #b71c1c; text-shadow: 3px 3px 6px #3e2723">Ecco cosa abbiamo realizzato</h1>
		<br>
		<div class="row">
			<div class="col-md-6">
  					<div class="gallery">
  						<h5 style="font-size: 1.2em; color: #b71c1c; font-weight: bold; ">Punish the Ghost | Early Vibes</h5>
		 	 		<iframe width="560" height="315" src="https://www.youtube.com/embed/isfsdtJ9JHw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		 	 		</div>
		 	</div>
		 	<div class="col-md-6">
		 		<div class="gallery">
  					<h5 style="font-size: 1em; color: #b71c1c; font-weight: bold">Tra Zena e l'Africa | U Carbun e Gente de Lugan</h5>
		 	 		<iframe width="560" height="315" src="https://www.youtube.com/embed/3vJRfAVvsEg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		 	 	</div>
		 	</div>
		 	<div class="col-md-6">
		 		<div class="gallery">
  					<h5 style="font-size: 1.2em; color: #b71c1c; font-weight: bold">Distanze | Lobina</h5>
		 	 		<iframe width="560" height="315" src="https://www.youtube.com/embed/iIuHQqGq0vg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		 	 	</div>
		 	</div>
		 	<div class="col-md-6">
		 		<div class="gallery">
  					<h5 style="font-size: 1.2em; color: #b71c1c; font-weight: bold">City Of Silences | f o l l o w t h e r i v e r</h5>
		 	 		<iframe width="560" height="315" src="https://www.youtube.com/embed/BClVtuEQDeo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		 	 	</div>
		 	</div>
 	 	</div>
 	</div>
</div>
</div>

app/views/static_pages/contattaci.html.erb
<% provide(:title, "Contatti") %>
<div class="contatti">
<div class="container">
	<div class="row center">
    	<div class="col-sm-12">
          	<h3><i class="mdi-content-send" style="color: #b71c1c"></i></h3>
          	<h1 style="color: #b71c1c; text-shadow: 3px 3px 6px #3e2723">Contattaci</h1>
          	<br>
          	<br>
        </div>
        	 <div class="col-sm-4">
              <div class="gallery-cont">
              	 <a href="https://wa.me/393891086664" target="_blank" class="center"><img class="icon-png" src="https://bitbucket.org/Cutdownrecords/cutdownrecords/raw/0f7880d9b79ba1deb104957a49833ed4f820aaf3/app/assets/images/whatsapp.png">
              	 <h5 class="center" style="color: #b71c1c; font-size: 2em">Whatsapp</h5></a>
              	 <br>
              	 <h5 class="light black-text" style="font-size: 1.5em" > Oppure chiamaci direttamente al 
                 <br>
                 <a href="tel:+393891086664" style="color: #b71c1c"> +39 389 1086664 </a>
                 <br>
                 o al 
                 <br>
                 <a href="tel:+393206277402" style="color: #b71c1c">+39 320 6277402</a></h5>
              </div>
         	 </div>

          	<div class="col-sm-4">
                <div class="gallery-cont">
              	 <a href="https://m.me/Cutdownrecords?fbclid=IwAR11xCvca_lH-i67cwr6WR5kYKES7ZCUWlD9K4MjBGpPsrdwSsd65Y0VwE0" target="_blank" class="center"><img class="icon-png" src="https://bitbucket.org/Cutdownrecords/cutdownrecords/raw/0f7880d9b79ba1deb104957a49833ed4f820aaf3/app/assets/images/messenger.png">
              	 <h5 class="center" style="color: #b71c1c; font-size: 2em">Messenger</h5></a>
              	 <br>
              	 <h5 class="light" style="font-size: 1.5em">Contattaci su Messenger e visita la nostra pagina. Già che ci sei metti qualche like, sono sempre i ben accetti!</h5>
                </div>
            </div>

          	 <div class="col-sm-4">
              <div class="gallery-cont">
              	 <a href="#email" class="center"><img class="icon-png" src="https://bitbucket.org/Cutdownrecords/cutdownrecords/raw/0f7880d9b79ba1deb104957a49833ed4f820aaf3/app/assets/images/email.png">
              	 <h5 class="center" style="color: #b71c1c; font-size: 2em">Email</h5></a>
              	 <br>
              	 <h5 class="light" style="font-size: 1.5em">Iscriviti alla nostra Newsletter per ricevere offerte e promozioni dedicate solo ai più fedeli.
              	 <br>
               	 Non esagereremo con lo Spam. Promesso!</h5>
              </div>
          	 </div>
          	<br>
      	
  	</div>
</div>
</div>

app/views/static_pages/home.html.erb
<div class="home">
	<div class="center container">
		<h1 class="sttl">Studio di registrazione, mixing e mastering.</h1>
          <br>
          <div class="row social-icon">
          	<div class="col-sm-4">
				<%= link_to image_tag("facebook.png", alt: "facebook"),
				            'https://www.facebook.com/pg/Cutdownrecords/posts/?ref=page_internal', target: "_blank" %></div>
			<div class="col-sm-4">	
				<%= link_to image_tag("insta.png", alt: "Instagram"),
				            'https://www.instagram.com/cutdownrecords/?hl=it', target: "_blank" %></div>
			<div class="col-sm-4">	
				<%= link_to image_tag("youtube.png", alt: "Youtube"),
				            'https://www.youtube.com/channel/UClRNlBbbKLEqBLtA31I1goQ', target: "_blank" %></div>
				</div>
			<div class="row">
			<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 jumbotron jumbotron-font-size">
				<div class="CDlogo">
				<%= link_to image_tag("LogoCD.png", alt: "CutDownlogo", size: 120),
				            'http://rubyonrails.org/' %>
			</div>
  				<h1>Benvenuto alla Cut Down</h1>

  				<h2>Questa è la nostra Home page</h2>


  			<%= link_to "Registrati!", signup_path, class: "btn btn-lg btn-danger" %>
  				<br>

				
				</div>
			</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>